volumes:
    postgres-data:
        external: true
services:
    postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES= passpro
            - POSTGRES_PASSWORD= password
            - POSTGRES_USER= passpro
        ports:
            - 15432:5432

    fastapi:
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        volumes:
            - ./api:/app
        environment:
            DATABASE_URL: postgresql://passpro:password@postgres:5432/passpro
            WAIT_HOSTS: postgres:5432
            SIGNING_KEY: 7da8b48fd9452fd24a812915812de86bf3c88683001ed934bed33f253387cbad

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: http://localhost:3000
            REACT_APP_API_HOST: http://localhost:8000
# ./glv-cloud-cli deploy -a fastapi -i registry.gitlab.com/pass-pro/app/api_image:latest -e SIGNING_KEY=7da8b48fd9452fd24a812915812de86bf3c88683001ed934bed33f253387cbad -e DATABASE_URL=postgresql://passpro:password@feb-23-pt-16-postgres-service.default.svc.cluster.local/passpro -e CORS_HOST=https://rc678-galvanize.gitlab.io
